#include "WordList.h"
#include <chrono>

using namespace std;

WordList::WordList() : head(nullptr) {
    // Initialize random number generator with time-based seed
    rng.seed(static_cast<unsigned int>(chrono::steady_clock::now().time_since_epoch().count()));
    
    // hahaha ang haba ano
    const string originalWords[] = {
        "apple",
        "banana",
        "orange",
        "grapes",
        "cherry",
        "antidisestablishmentarianism",
        "pneumonoultramicroscopicsilicovolcanoconiosis",
        "hippopotomonstrosesquippedaliophobia",
        "supercalifragilisticexpialidocious",
        "incomprehensibilities",
        "parasternocleidomastoid",
        "psychoneuroendocrinological",
        "electroencephalographically",
        "gastrointestinal",
        "disproportionableness",
        "microspectrophotometrically",
        "ultramicroscopically",
        "quasiperiodically",
        "immunoelectrophoretically",
        "uncharacteristically",
        "micrometeorological",
        "unintelligibleness",
        "interconnectedness",
        "deinstitutionalization",
        "photophosphorylation",
        "counterdemonstration",
        "dihydroxyacetonephosphate",
        "palaeogeographically",
        "extemporaneousness",
        "overintellectualization",
        "indistinguishableness",
        "counterproliferation",
        "immunohematologically",
        "chromolithographically",
        "nondiscrimination",
        "thermoelectrically",
        "antirevolutionaries",
        "inconsequentialities",
        "mischaracterization",
        "electroretinographies",
        "psychopathologically",
        "microencapsulations",
        "immunoelectrophoresis",
        "counterintelligence",
        "incommensurabilities",
        "disproportionateness",
        "ultramicroscopical",
        "phenomenalistically",
        "immunocytochemistry",
        "irreconcilabilities",
        "unintelligibilities",
        "overenthusiastically",
        "pseudopseudohypoparathyroidism",
        "photointerpretation",
        "underrepresentation",
        "ultrasonographically",
        "neuroradiologically",
        "anthropomorphologically",
        "counterinflationary",
        "phosphatidylethanolamine",
        "immunoprecipitation",
        "overcommunication",
        "unintelligibility",
        "circumlocutionary",
        "electrooculographic",
        "anticonstitutional",
        "unconstitutionality",
        "neuropharmacological",
        "counterproductive",
        "irreproachableness",
        "spectrophotometries",
        "microphotometrically",
        "immunohistochemistry",
        "counterpropagations",
        "stereomicroscopical",
        "uncontrollableness",
        "photoreconnaissance",
        "incontrovertibility",
        "inconspicuousnesses",
        "immunopathological",
        "uncontroversially",
        "incomprehensibility",
        "immunomodulations",
        "suprasegmentalities",
        "contradistinctively",
        "antiestablishmentarian",
        "psychobiographical",
        "unconscionableness",
        "overproportionately",
        "microcalorimetrical",
        "unquestionableness",
        "ultracentrifugation",
        "counterinsurgencies",
        "neurotransmitter",
        "counterprogramming",
        "multidimensionality",
        "disestablishmentarian",
        "photogrammetries",
        "countercultural",
        "uncharacterized",
        "microelectronically",
        "noncontroversial",
        "uncharacteristic",
        "thermoluminescent",
        "inefficaciousnesses",
        "counterinstitutional",
        "electrocardiographic",
        "immunocompetent",
        "counterretaliation",
        "microcrystalline",
        "indistinguishability",
        "antireductionism",
        "immunogenetically",
        "thermoregulations",
        "photomicrography",
        "countercondensation",
        "psychopathological",
        "microcirculation",
        "counteraccusation",
        "hyperintellectual",
        "electroacoustic",
        "counterreformation",
        "noninterventional",
        "superinjunction",
        "neuropeptidases",
        "deoxyribonucleotide",
        "microlepidopterous",
        "ultrarevolutionary",
        "immunoperoxidase",
        "hyperaggressiveness",
        "supercontinental",
        "dehydrochlorinate",
        "unconventionality",
        "indistinctiveness",
        "counterdemonstrator",
        "extraterrestrial",
        "counterexplanation",
        "microinstruction",
        "thermoperiodicity",
        "overidentification",
        "photosynthetically",
        "psychophysiological",
        "immunocompromised",
        "indeterminateness",
        "nonreproducibility",
        "counterdisengagement",
        "microvasculature",
        "psychotomimetic",
        "deindustrialization",
        "underutilization",
        "counterguerilla",
        "counterdeployment",
        "antiparliamentarian",
        "ultraradicalism",
        "counterproliferative",
        "microevolutionary",
        "supererogatorily",
        "immunodiagnostic",
        "intercontinental",
        "photosensitization",
        "counterespionage",
        "deconstructionist",
        "psychophysicist",
        "microenvironmental",
        "ultrarevolutionaries",
        "counterdeployment",
        "immunosuppressive",
        "mispronunciation",
        "counterirritation",
        "noncomprehension",
        "antinationalistic",
        "photosensitivity",
        "counterinstitutional",
        "neurofibromatosis",
        "ultrasegregationist",
        "immunogenicity",
        "misinterpretation",
        "microsporogenesis",
        "counterprogramming",
        "decontamination",
        "photodissociation",
        "interdependence",
        "anticonventional",
        "counterprojection",
        "deindustrialization",
        "ultracrepidarianism",
        "immunotherapeutic",
        "intergovernmental",
        "counterreformation",
        "photosynthetize",
        "electrotherapeutic",
        "ultramicroanalysis",
        "counteraggression",
        "misidentification",
        "micropropagation",
        "counterproposition",
        "superregeneration",
        "indiscernibility",
        "counterrecruitment",
        "photosynthesizing",
        "hyperstimulation",
        "immunohematologist",
        "interrelationship",
        "microdissection",
        "psychotomimetically",
        "indigestibleness",
        "counterretaliate",
        "ultrafastidiousness",
        "counterrevelation",
        "photosynthetically",
        "immunoreactivity",
        "superparamagnetic",
        "indubitableness",
        "photoperiodically",
        "countersecessionist",
        "interconvertibility",
        "microfabrication",
        "counterreformationist",
        "antiparliamentarianism",
        "photosynthesizer",
        "psycholinguistically",
        "superregenerative",
        "ulrarevolutionary",
        "counterdeclaration",
        "immunohematological",
        "indemonstrability",
        "counterincitement",
        "photomechanically",
        "microaerophilic",
        "hyperimmunizations",
        "counterattraction",
        "immunomodulation",
        "antipersonnel",
        "photophosphorylating",
        "microcalorimetrically",
        "counterestablishment",
        "ultramicrotomist",
        "dehydrochlorinase",
        "counterespionages",
        "immunopathologically",
        "neurophysiological",
        "intercommunication",
        "psychogeriatrician",
        "microearthquake",
        "counterreformationary",
        "indistinctivenesses",
        "antiperspirant",
        "counteraggression",
        "dehydrochlorination",
        "ultrarightist",
        "immunodiagnoses",
        "psychopathological",
        "neurofibromatoses",
        "microphotographic",
        "counterirritations",
        "mispronunciations",
        "superintelligence",
        "immunocytochemical",
        "interprofessional",
        "photosynthetically",
        "counterrevelations",
        "ultrasegregationists",
        "counterreformations",
        "microspectrophotometer",
        "deindustrializations",
        "immunohematologists",
        "superindustrialization",
        "interdenominational",
        "counterconditioning",
        "psychobiographical",
        "neurophysiologically",
        "antiferromagnetic",
        "counterproliferations",
        "dehydrochlorinations",
        "immunoelectrophoresis",
        "indistinctiveness",
        "counterdemonstrations",
        "ultramicroscopical",
        "counterintuitive",
        "photosynthetically",
        "immunomodulatory",
        "hyperpigmentation",
        "superconglomerate",
        "counterconditioned",
        "microphotographers",
        "deindustrializing",
        "counterdeployment",
        "psychophysiological",
        "neuroendocrinologist",
        "immunomodulating",
        "ultrarevolutionary",
        "photosensitivities",
        "indeterminatenesses",
        "counterexplanation",
        "antiepileptically",
        "counterinfluences",
        "photosynthetically",
        "microcircuitry",
        "interconnectivity",
        "counterinhibition"
    };
    // Add all these words to our linked list
    for (const string& word : originalWords) {
        insertWord(word);
    }
}

void WordList::insertWord(const string& word) {
    // Adds a new word to the end of the linked list
    auto newNode = make_unique<WordNode>(word);
    if (!head) {
        head = move(newNode); // First word gets to be the head
    } else {
        WordNode* current = head.get();
        while (current->next) {
            current = current->next.get(); // Move to the end of the list
        }
        current->next = move(newNode); // Attach the new word
    }
}

string WordList::getRandomWord() {
    if (!head) return ""; // Return empty string para pag nalimutan ko iadd yung word list
    
    // Count how many words
    int count = 0;
    WordNode* current = head.get();
    while (current) {
        count++;
        current = current->next.get();
    }
    
    // Better randomization using mt19937
    uniform_int_distribution<int> dist(0, count - 1);
    int randomIndex = dist(rng);

    // Find the word at that index
    current = head.get();
    for (int i = 0; i < randomIndex && current != nullptr; i++) {
        current = current->next.get();
    }

    return current ? current->word : ""; // Return the chosen word with null check
}